// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboardText():Promise<string>;

export function StartLLMStream(arg1:string):Promise<void>;
