// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboardText():Promise<string>;

export function GetLLMConfig():Promise<string>;

export function SetLLMConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartLLMStream(arg1:string):Promise<void>;
