// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function StartLLMStream(arg1) {
  return window['go']['main']['App']['StartLLMStream'](arg1);
}
